/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_jorgezuniga;

import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class MainLab7_JorgeZuniga extends javax.swing.JFrame {

    /**
     * Creates new form MainLab7_JorgeZuniga
     */
    public MainLab7_JorgeZuniga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearUsuarios = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NombreAddAlumno = new javax.swing.JTextField();
        UsuarioAddAlumno = new javax.swing.JTextField();
        ApellidoAddAlumno = new javax.swing.JTextField();
        ContraAddAlumno = new javax.swing.JTextField();
        GuardarAddAlumno = new javax.swing.JButton();
        SalirCrearAlumno = new javax.swing.JButton();
        CrearCompilador = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        CrearCompiladores = new javax.swing.JButton();
        CrearUsuariosAlumnos = new javax.swing.JButton();
        Compilar = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Usuario");

        jLabel4.setText("Contrasena");

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel5.setText("Crear Usuarios de Alumnos");

        GuardarAddAlumno.setText("Guardar");
        GuardarAddAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarAddAlumnoMouseClicked(evt);
            }
        });

        SalirCrearAlumno.setText("Salir");
        SalirCrearAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirCrearAlumnoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CrearUsuariosLayout = new javax.swing.GroupLayout(CrearUsuarios.getContentPane());
        CrearUsuarios.getContentPane().setLayout(CrearUsuariosLayout);
        CrearUsuariosLayout.setHorizontalGroup(
            CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UsuarioAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ApellidoAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(111, 111, 111)
                        .addComponent(NombreAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuardarAddAlumno)
                            .addComponent(ContraAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(SalirCrearAlumno)
                .addGap(36, 36, 36))
        );
        CrearUsuariosLayout.setVerticalGroup(
            CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ApellidoAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UsuarioAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ContraAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarAddAlumno)
                    .addComponent(SalirCrearAlumno))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout CrearCompiladorLayout = new javax.swing.GroupLayout(CrearCompilador.getContentPane());
        CrearCompilador.getContentPane().setLayout(CrearCompiladorLayout);
        CrearCompiladorLayout.setHorizontalGroup(
            CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        CrearCompiladorLayout.setVerticalGroup(
            CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CrearCompiladores.setText("Crear Compiladores");
        CrearCompiladores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCompiladoresMouseClicked(evt);
            }
        });

        CrearUsuariosAlumnos.setText("Crear Usuarios Alumnos");
        CrearUsuariosAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuariosAlumnosMouseClicked(evt);
            }
        });

        Compilar.setText("Compilar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Compilar)
                    .addComponent(CrearUsuariosAlumnos)
                    .addComponent(CrearCompiladores))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(CrearCompiladores)
                .addGap(75, 75, 75)
                .addComponent(CrearUsuariosAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(Compilar)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarAddAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarAddAlumnoMouseClicked
        // TODO add your handling code here:
        try {
            boolean entra = true;
            if (NombreAddAlumno.getText() == null || ApellidoAddAlumno.getText() == null
                    || UsuarioAddAlumno.getText() == null || ContraAddAlumno.getText() == null) {
                entra = false;
                JOptionPane.showMessageDialog(null, "No se puede crear usuario por que hay campos vacios");
            }
            if (entra) {

                AdministrarUsuarios ap1 = new AdministrarUsuarios("./UsuariosA.jz");
                ap1.cargarArchivo();
                boolean entra1 = true;
                for (int i = 0; i <= ap1.getListaUsuariosAlumnos().size() - 1; i++) {
                    if ((UsuarioAddAlumno.getText().equals(ap1.getListaUsuariosAlumnos().get(i).getUsuario()))) {
                        JOptionPane.showMessageDialog(null, "Usuario ya existente!!");
                        entra1 = false;
                        break;
                    } else if ((ContraAddAlumno.getText().equals((ap1.getListaUsuariosAlumnos().get(i).getContrasena())))) {
                        JOptionPane.showMessageDialog(null, "Contrasena ya existente!!");
                        entra1 = false;
                        break;
                    }
                }
                if (entra1) {
                    String nombre, apellido, usuario, contra;
                    nombre = NombreAddAlumno.getText();
                    apellido = ApellidoAddAlumno.getText();
                    usuario = UsuarioAddAlumno.getText();
                    contra = ContraAddAlumno.getText();

                    UsuariosAlumnos p = new UsuariosAlumnos(nombre, apellido, usuario, contra);
                    AdministrarUsuarios ap = new AdministrarUsuarios("./UsuariosA.jz");
                    ap.cargarArchivo();
                    ap.setUsuarioAlumno(p);
                    ap.escribirArchivo();
                    JOptionPane.showMessageDialog(this, "Usuario guardado exitosamente");
                    NombreAddAlumno.setText("");
                    ApellidoAddAlumno.setText("");
                    UsuarioAddAlumno.setText("");
                    ContraAddAlumno.setText("");
                }

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_GuardarAddAlumnoMouseClicked

    private void CrearUsuariosAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuariosAlumnosMouseClicked
        // TODO add your handling code here:
        try {
            CrearUsuarios.pack();
            CrearUsuarios.setLocationRelativeTo(null);
            CrearUsuarios.setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_CrearUsuariosAlumnosMouseClicked

    private void SalirCrearAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirCrearAlumnoMouseClicked
        // TODO add your handling code here:
        try {
            this.pack();
            this.setLocationRelativeTo(null);
            this.setVisible(true);
            CrearUsuarios.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SalirCrearAlumnoMouseClicked

    private void CrearCompiladoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCompiladoresMouseClicked
        // TODO add your handling code here:
        try {
            AdministrarUsuarios ap = new AdministrarUsuarios("./UsuariosA.jz");
            ap.cargarArchivo();
            if (ap.getListaUsuariosAlumnos().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se pueden crear compiladores sin tener Alumnos!!");
            } else {
                CrearCompilador.pack();
                CrearCompilador.setLocationRelativeTo(null);
                CrearCompilador.setVisible(true);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_CrearCompiladoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLab7_JorgeZuniga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLab7_JorgeZuniga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLab7_JorgeZuniga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLab7_JorgeZuniga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLab7_JorgeZuniga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoAddAlumno;
    private javax.swing.JButton Compilar;
    private javax.swing.JTextField ContraAddAlumno;
    private javax.swing.JDialog CrearCompilador;
    private javax.swing.JButton CrearCompiladores;
    private javax.swing.JDialog CrearUsuarios;
    private javax.swing.JButton CrearUsuariosAlumnos;
    private javax.swing.JButton GuardarAddAlumno;
    private javax.swing.JTextField NombreAddAlumno;
    private javax.swing.JButton SalirCrearAlumno;
    private javax.swing.JTextField UsuarioAddAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
