/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_jorgezuniga;

import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class MainLab7_JorgeZuniga extends javax.swing.JFrame {

    /**
     * Creates new form MainLab7_JorgeZuniga
     */
    public MainLab7_JorgeZuniga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearCompilador = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        GuardarCompiladoress = new javax.swing.JButton();
        SalirCrearCompiladores = new javax.swing.JButton();
        NombreAddCompilador = new javax.swing.JTextField();
        LineasLexico = new javax.swing.JTextField();
        LineasSemantico = new javax.swing.JTextField();
        LineasSintactico = new javax.swing.JTextField();
        Generador = new javax.swing.JTextField();
        Optimizacion = new javax.swing.JTextField();
        Intermedio = new javax.swing.JTextField();
        NombreCreadorAddCompilador = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaSimbolos = new javax.swing.JTable();
        MenuUsuarios = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        Sigin = new javax.swing.JButton();
        Sig = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NombreAddAlumno = new javax.swing.JTextField();
        UsuarioAddAlumno = new javax.swing.JTextField();
        ApellidoAddAlumno = new javax.swing.JTextField();
        ContraAddAlumno = new javax.swing.JTextField();
        GuardarAddAlumno = new javax.swing.JButton();
        SalirCrearAlumno = new javax.swing.JButton();
        Log = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        UsuarioLog = new javax.swing.JTextField();
        ContraLog = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        LogSuperUsuario = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        SuperContra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        SuperUsuario = new javax.swing.JTextField();
        EntrarCompilaciones = new javax.swing.JButton();
        SalirLogSuper = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Compilar = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        ListaAlumnos = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();
        P2 = new javax.swing.JProgressBar();
        P1 = new javax.swing.JProgressBar();
        ComilarPrograma = new javax.swing.JButton();
        SalidaCompilar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        OpcionesUsuario = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        VerNota = new javax.swing.JButton();
        UsuarioLLLLL = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        MenuSuperUsuario = new javax.swing.JButton();
        Usuarios = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        jLabel6.setText("Alumno");

        jLabel7.setText("Nombre del compilador");

        jLabel8.setText("Analisis Lexico");

        jLabel9.setText("Analisis Sintactico");

        jLabel10.setText("Analisis Semantico");

        jLabel11.setText("Generacion de Codigo Intermedio");

        jLabel12.setText("Optimizacion Codigo");

        jLabel13.setText("Generador Codigo");

        GuardarCompiladoress.setText("Guardar");
        GuardarCompiladoress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarCompiladoressMouseClicked(evt);
            }
        });

        SalirCrearCompiladores.setText("Salir");
        SalirCrearCompiladores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirCrearCompiladoresMouseClicked(evt);
            }
        });

        TablaSimbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Simbolos", "Significado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaSimbolos);

        javax.swing.GroupLayout CrearCompiladorLayout = new javax.swing.GroupLayout(CrearCompilador.getContentPane());
        CrearCompilador.getContentPane().setLayout(CrearCompiladorLayout);
        CrearCompiladorLayout.setHorizontalGroup(
            CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCompiladorLayout.createSequentialGroup()
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearCompiladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)))
                    .addGroup(CrearCompiladorLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(GuardarCompiladoress)))
                .addGap(27, 27, 27)
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Generador, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(Optimizacion)
                    .addComponent(Intermedio)
                    .addComponent(LineasSemantico)
                    .addComponent(NombreCreadorAddCompilador)
                    .addComponent(NombreAddCompilador)
                    .addComponent(LineasLexico)
                    .addComponent(LineasSintactico))
                .addGap(18, 18, 18)
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearCompiladorLayout.createSequentialGroup()
                        .addGap(0, 165, Short.MAX_VALUE)
                        .addComponent(SalirCrearCompiladores))
                    .addGroup(CrearCompiladorLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        CrearCompiladorLayout.setVerticalGroup(
            CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearCompiladorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NombreCreadorAddCompilador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NombreAddCompilador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CrearCompiladorLayout.createSequentialGroup()
                        .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(LineasLexico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(LineasSintactico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(LineasSemantico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Intermedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Optimizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Generador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(CrearCompiladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarCompiladoress)
                    .addComponent(SalirCrearCompiladores))
                .addContainerGap())
        );

        login.setText("Log In");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        Sigin.setText("Sig In");
        Sigin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sigin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(Sigin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout MenuUsuariosLayout = new javax.swing.GroupLayout(MenuUsuarios.getContentPane());
        MenuUsuarios.getContentPane().setLayout(MenuUsuariosLayout);
        MenuUsuariosLayout.setHorizontalGroup(
            MenuUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuUsuariosLayout.setVerticalGroup(
            MenuUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Usuario");

        jLabel4.setText("Contrasena");

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel5.setText("Crear Usuarios de Alumnos");

        GuardarAddAlumno.setText("Guardar");
        GuardarAddAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarAddAlumnoMouseClicked(evt);
            }
        });

        SalirCrearAlumno.setText("Salir");
        SalirCrearAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirCrearAlumnoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SigLayout = new javax.swing.GroupLayout(Sig.getContentPane());
        Sig.getContentPane().setLayout(SigLayout);
        SigLayout.setHorizontalGroup(
            SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SigLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(SigLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SigLayout.createSequentialGroup()
                        .addGroup(SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UsuarioAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ApellidoAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(111, 111, 111)
                                .addComponent(NombreAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContraAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SigLayout.createSequentialGroup()
                        .addComponent(GuardarAddAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SalirCrearAlumno)
                        .addGap(53, 53, 53))))
        );
        SigLayout.setVerticalGroup(
            SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ApellidoAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UsuarioAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ContraAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(SigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarAddAlumno)
                    .addComponent(SalirCrearAlumno))
                .addGap(47, 47, 47))
        );

        jLabel14.setText("Usuario");

        jLabel15.setText("Contrasena");

        Entrar.setText("Entrar");
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarMouseClicked(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel16.setText("Entrar");

        javax.swing.GroupLayout LogLayout = new javax.swing.GroupLayout(Log.getContentPane());
        Log.getContentPane().setLayout(LogLayout);
        LogLayout.setHorizontalGroup(
            LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogLayout.createSequentialGroup()
                .addGroup(LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(LogLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UsuarioLog, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContraLog, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(Entrar)
                                .addGap(98, 98, 98)
                                .addComponent(jButton2))))
                    .addGroup(LogLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        LogLayout.setVerticalGroup(
            LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ContraLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrar)
                    .addComponent(jButton2))
                .addGap(65, 65, 65))
        );

        jLabel17.setText("Contrasena");

        jLabel18.setText("Usuario");

        EntrarCompilaciones.setText("Entrar");
        EntrarCompilaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarCompilacionesMouseClicked(evt);
            }
        });

        SalirLogSuper.setText("Salir");
        SalirLogSuper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirLogSuperMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel19.setText("Entrar Super Usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SuperUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SuperContra, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(EntrarCompilaciones)
                            .addGap(98, 98, 98)
                            .addComponent(SalirLogSuper))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel19)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuperUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(SuperContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntrarCompilaciones)
                    .addComponent(SalirLogSuper))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout LogSuperUsuarioLayout = new javax.swing.GroupLayout(LogSuperUsuario.getContentPane());
        LogSuperUsuario.getContentPane().setLayout(LogSuperUsuarioLayout);
        LogSuperUsuarioLayout.setHorizontalGroup(
            LogSuperUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogSuperUsuarioLayout.setVerticalGroup(
            LogSuperUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel21.setText("Alumno");

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Errores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaErrores);

        ComilarPrograma.setText("Compilar");
        ComilarPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComilarProgramaMouseClicked(evt);
            }
        });

        SalidaCompilar.setText("Salida");
        SalidaCompilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalidaCompilarMouseClicked(evt);
            }
        });

        jLabel22.setText("Fase Analisis");

        jLabel23.setText("Fase Sintesis");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ComilarPrograma))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalidaCompilar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalidaCompilar)
                    .addComponent(ComilarPrograma))
                .addContainerGap())
        );

        javax.swing.GroupLayout CompilarLayout = new javax.swing.GroupLayout(Compilar.getContentPane());
        Compilar.getContentPane().setLayout(CompilarLayout);
        CompilarLayout.setHorizontalGroup(
            CompilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CompilarLayout.setVerticalGroup(
            CompilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompilarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Crear Compilador");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        VerNota.setText("Ver Nota");
        VerNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerNotaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsuarioLLLLL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VerNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addGap(47, 47, 47)
                .addComponent(UsuarioLLLLL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(VerNota)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout OpcionesUsuarioLayout = new javax.swing.GroupLayout(OpcionesUsuario.getContentPane());
        OpcionesUsuario.getContentPane().setLayout(OpcionesUsuarioLayout);
        OpcionesUsuarioLayout.setHorizontalGroup(
            OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OpcionesUsuarioLayout.setVerticalGroup(
            OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuSuperUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MenuSuperUsuario.setText("Super Usuario");
        MenuSuperUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSuperUsuarioMouseClicked(evt);
            }
        });

        Usuarios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Usuarios.setText("Usuarios");
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuariosMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel20.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel20)
                    .addComponent(Usuarios)
                    .addComponent(MenuSuperUsuario))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel20)
                .addGap(62, 62, 62)
                .addComponent(Usuarios)
                .addGap(120, 120, 120)
                .addComponent(MenuSuperUsuario)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarAddAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarAddAlumnoMouseClicked
        // TODO add your handling code here:
        try {
            boolean entra = true;
            if (NombreAddAlumno.getText() == null || ApellidoAddAlumno.getText() == null
                    || UsuarioAddAlumno.getText() == null || ContraAddAlumno.getText() == null) {
                entra = false;
                JOptionPane.showMessageDialog(null, "No se puede crear usuario por que hay campos vacios");
            }
            if (entra) {

                AdministrarUsuarios ap1 = new AdministrarUsuarios("./UsuariosA.jz");
                ap1.cargarArchivo();
                boolean entra1 = true;
                for (int i = 0; i <= ap1.getListaUsuariosAlumnos().size() - 1; i++) {
                    if ((UsuarioAddAlumno.getText().equals(ap1.getListaUsuariosAlumnos().get(i).getUsuario()))) {
                        JOptionPane.showMessageDialog(null, "Usuario ya existente!!");
                        entra1 = false;
                        break;
                    } else if ((ContraAddAlumno.getText().equals((ap1.getListaUsuariosAlumnos().get(i).getContrasena())))) {
                        JOptionPane.showMessageDialog(null, "Contrasena ya existente!!");
                        entra1 = false;
                        break;
                    }
                }
                if (entra1) {
                    String nombre, apellido, usuario, contra;
                    nombre = NombreAddAlumno.getText();
                    apellido = ApellidoAddAlumno.getText();
                    usuario = UsuarioAddAlumno.getText();
                    contra = ContraAddAlumno.getText();

                    UsuariosAlumnos p = new UsuariosAlumnos(nombre, apellido, usuario, contra);
                    AdministrarUsuarios ap = new AdministrarUsuarios("./UsuariosA.jz");
                    ap.cargarArchivo();
                    ap.setUsuarioAlumno(p);
                    ap.escribirArchivo();
                    JOptionPane.showMessageDialog(this, "Usuario guardado exitosamente");
                    NombreAddAlumno.setText("");
                    ApellidoAddAlumno.setText("");
                    UsuarioAddAlumno.setText("");
                    ContraAddAlumno.setText("");
                }

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_GuardarAddAlumnoMouseClicked

    private void SalirCrearAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirCrearAlumnoMouseClicked
        // TODO add your handling code here:
        try {
            MenuUsuarios.pack();
            MenuUsuarios.setLocationRelativeTo(null);
            MenuUsuarios.setVisible(true);
            Sig.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SalirCrearAlumnoMouseClicked

    private void SalirCrearCompiladoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirCrearCompiladoresMouseClicked
        // TODO add your handling code here:
        try {
            this.setLocationRelativeTo(null);
            this.pack();
            this.setVisible(true);
            CrearCompilador.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SalirCrearCompiladoresMouseClicked

    private void GuardarCompiladoressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCompiladoressMouseClicked
        // TODO add your handling code here:
        try {

            AministrarCompiladores ap = new AministrarCompiladores("./Compiladores.jz");
            ap.cargarArchivo();
            String nombreCompilador, nombreCreador;
            int lexico, sintactico, semantico, intermedio, optimizador, generador;
            JTable tabla;
            nombreCompilador = NombreAddCompilador.getText();
            nombreCreador = NombreCreadorAddCompilador.getText();
            lexico = Integer.parseInt(LineasLexico.getText());
            sintactico = Integer.parseInt(LineasSintactico.getText());
            semantico = Integer.parseInt(LineasSemantico.getText());

            intermedio = Integer.parseInt(Intermedio.getText());
            optimizador = Integer.parseInt(Optimizacion.getText());
            generador = Integer.parseInt(Generador.getText());
            tabla = (JTable) TablaSimbolos.getCellEditor();
            Compiladores p = new Compiladores(nombreCompilador, nombreCreador, lexico, sintactico, semantico, intermedio, optimizador, generador, tabla);

            ap.setCompiladores(p);
            ap.escribirArchivo();

            JOptionPane.showMessageDialog(this, "Compiladore guardado exitosamente");
            NombreAddCompilador.setText("");
            LineasLexico.setText("");
            LineasSintactico.setText("");
            LineasSemantico.setText("");
            Intermedio.setText("");
            Optimizacion.setText("");
            Generador.setText("");
            TablaSimbolos.setToolTipText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_GuardarCompiladoressMouseClicked

    private void SiginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiginMouseClicked
        // TODO add your handling code here:
        try {
            Sig.setLocationRelativeTo(null);
            Sig.pack();
            Sig.setVisible(true);
            MenuUsuarios.setVisible(false);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_SiginMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        try {
            Log.setLocationRelativeTo(null);
            Log.pack();
            Log.setVisible(true);
            MenuUsuarios.setVisible(false);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_loginMouseClicked

    private void UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseClicked
        // TODO add your handling code here:
        try {
            MenuUsuarios.setLocationRelativeTo(null);
            MenuUsuarios.pack();
            MenuUsuarios.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_UsuariosMouseClicked

    private void EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseClicked
        // TODO add your handling code here:
        String nombreAlumno;
        try {
            AdministrarUsuarios ap = new AdministrarUsuarios("./UsuariosA.jz");
            ap.cargarArchivo();
            boolean entro = true;
            for (int i = 0; i <= ap.getListaUsuariosAlumnos().size() - 1; i++) {
                if (UsuarioLog.getText().equals(ap.getListaUsuariosAlumnos().get(i).getUsuario())
                        && ContraLog.getText().equals(ap.getListaUsuariosAlumnos().get(i).getContrasena())) {

                    OpcionesUsuario.pack();
                    OpcionesUsuario.setLocationRelativeTo(null);
                    OpcionesUsuario.setVisible(true);
                    Log.setVisible(false);
                    UsuarioLLLLL.setText(UsuarioLog.getText());
                    UsuarioLLLLL.setVisible(false);
                    UsuarioLog.setText("");
                    ContraLog.setText("");
                    nombreAlumno = ap.getListaUsuariosAlumnos().get(i).getNombre();
                    NombreCreadorAddCompilador.setText(nombreAlumno);
                    entro = true;
                    break;
                } else {
                    entro = false;
                }
            }
            if (entro == false) {
                JOptionPane.showMessageDialog(null, "Contrasena o usuario incorrecto!!");
            }
            UsuarioLog.setText("");
            ContraLog.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_EntrarMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            MenuUsuarios.setLocationRelativeTo(null);
            MenuUsuarios.pack();
            MenuUsuarios.setVisible(true);
            Log.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void EntrarCompilacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarCompilacionesMouseClicked
        // TODO add your handling code here:
        try {
            AdministrarSuper ap = new AdministrarSuper("./SuperU.jz");
            ap.cargarArchivo();
            boolean entro = true;
            for (int i = 0; i <= ap.getListaSuperUsuario().size() - 1; i++) {
                if (SuperUsuario.getText().equals(ap.getListaSuperUsuario().get(i).getUsuario())
                        && SuperContra.getText().equals(ap.getListaSuperUsuario().get(i).getContrasena())) {

                    Compilar.pack();
                    Compilar.setLocationRelativeTo(null);
                    Compilar.setVisible(true);
                    LogSuperUsuario.setVisible(false);

                    SuperUsuario.setText("");
                    SuperContra.setText("");

                    AministrarCompiladores ap1 = new AministrarCompiladores("./Compiladores.jz");
                    ap1.cargarArchivo();
                    DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap1.getListaCompiladores().toArray());
                    ListaAlumnos.setModel(modelo);

                    entro = true;
                    break;
                } else {
                    entro = false;
                }
            }
            if (entro == false) {
                JOptionPane.showMessageDialog(null, "Contrasena o usuario incorrecto!!");
            }
            UsuarioLog.setText("");
            ContraLog.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_EntrarCompilacionesMouseClicked

    private void SalirLogSuperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirLogSuperMouseClicked
        // TODO add your handling code here:
        try {
            LogSuperUsuario.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SalirLogSuperMouseClicked

    private void MenuSuperUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSuperUsuarioMouseClicked
        // TODO add your handling code here:
        try {
            LogSuperUsuario.setLocationRelativeTo(null);
            LogSuperUsuario.pack();
            LogSuperUsuario.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_MenuSuperUsuarioMouseClicked

    private void SalidaCompilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalidaCompilarMouseClicked
        // TODO add your handling code here:
        try {
            this.setLocationRelativeTo(null);
            this.pack();
            this.setVisible(true);
            Compilar.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SalidaCompilarMouseClicked

    private void ComilarProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComilarProgramaMouseClicked
        // TODO add your handling code here:
        try {
            String nombre = ListaAlumnos.getSelectedItem().toString();
            P1.setValue(0);
            P2.setValue(0);
            AministrarCompiladores ap = new AministrarCompiladores("./Compiladores.jz");
            ap.cargarArchivo();
            int Analisis1;
            int Analisis2;
            int Analisis3;
            Analisis1 = ap.getListaCompiladores().get(ListaAlumnos.getSelectedIndex()).getLexico();
            Analisis2 = ap.getListaCompiladores().get(ListaAlumnos.getSelectedIndex()).getSintactico();
            Analisis3 = ap.getListaCompiladores().get(ListaAlumnos.getSelectedIndex()).getSemantico();
            this.P1.setMaximum(10);
            HiloFaseAnalisis H1 = new HiloFaseAnalisis(nombre, this.P1, true, Analisis1, Analisis2, Analisis3, this.tablaErrores);
            H1.start();

            if (P1.getValue()==P1.getMaximum()) {
                String nombre1 = ListaAlumnos.getSelectedItem().toString();
                AministrarCompiladores ap1 = new AministrarCompiladores("./Compiladores.jz");
                ap1.cargarArchivo();
                int Analisis4;
                int Analisis5;
                int Analisis6;
                Analisis4 = ap.getListaCompiladores().get(ListaAlumnos.getSelectedIndex()).getIntermedio();
                Analisis5 = ap.getListaCompiladores().get(ListaAlumnos.getSelectedIndex()).getOptimizador();
                Analisis6 = ap.getListaCompiladores().get(ListaAlumnos.getSelectedIndex()).getGenerador();
                this.P2.setMaximum(10);
                HiloFaseAnalisis H2 = new HiloFaseAnalisis(nombre1, this.P2, true, Analisis4, Analisis5, Analisis6, this.tablaErrores);
                H2.start();

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_ComilarProgramaMouseClicked

    private void VerNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerNotaMouseClicked
        // TODO add your handling code here:
        try {
            AdministrarUsuarios ap = new AdministrarUsuarios("./UsuariosA.jz");
            ap.cargarArchivo();
            for (int i = 0; i <= ap.getListaUsuariosAlumnos().size() - 1; i++) {
                if (ap.getListaUsuariosAlumnos().get(0).getUsuario().equals(UsuarioLLLLL.getText())) {
                    JOptionPane.showMessageDialog(null, "Su nota es:" + ap.getListaUsuariosAlumnos().get(0).getNota());
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_VerNotaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            CrearCompilador.setLocationRelativeTo(null);
            CrearCompilador.pack();
            CrearCompilador.setVisible(true);
            OpcionesUsuario.setVisible(false);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLab7_JorgeZuniga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLab7_JorgeZuniga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLab7_JorgeZuniga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLab7_JorgeZuniga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLab7_JorgeZuniga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoAddAlumno;
    private javax.swing.JButton ComilarPrograma;
    private javax.swing.JDialog Compilar;
    private javax.swing.JTextField ContraAddAlumno;
    private javax.swing.JTextField ContraLog;
    private javax.swing.JDialog CrearCompilador;
    private javax.swing.JButton Entrar;
    private javax.swing.JButton EntrarCompilaciones;
    private javax.swing.JTextField Generador;
    private javax.swing.JButton GuardarAddAlumno;
    private javax.swing.JButton GuardarCompiladoress;
    private javax.swing.JTextField Intermedio;
    private javax.swing.JTextField LineasLexico;
    private javax.swing.JTextField LineasSemantico;
    private javax.swing.JTextField LineasSintactico;
    private javax.swing.JComboBox<String> ListaAlumnos;
    private javax.swing.JDialog Log;
    private javax.swing.JDialog LogSuperUsuario;
    private javax.swing.JButton MenuSuperUsuario;
    private javax.swing.JDialog MenuUsuarios;
    private javax.swing.JTextField NombreAddAlumno;
    private javax.swing.JTextField NombreAddCompilador;
    private javax.swing.JTextField NombreCreadorAddCompilador;
    private javax.swing.JDialog OpcionesUsuario;
    private javax.swing.JTextField Optimizacion;
    private javax.swing.JProgressBar P1;
    private javax.swing.JProgressBar P2;
    private javax.swing.JButton SalidaCompilar;
    private javax.swing.JButton SalirCrearAlumno;
    private javax.swing.JButton SalirCrearCompiladores;
    private javax.swing.JButton SalirLogSuper;
    private javax.swing.JDialog Sig;
    private javax.swing.JButton Sigin;
    private javax.swing.JTextField SuperContra;
    private javax.swing.JTextField SuperUsuario;
    private javax.swing.JTable TablaSimbolos;
    private javax.swing.JTextField UsuarioAddAlumno;
    private javax.swing.JTextField UsuarioLLLLL;
    private javax.swing.JTextField UsuarioLog;
    private javax.swing.JButton Usuarios;
    private javax.swing.JButton VerNota;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton login;
    private javax.swing.JTable tablaErrores;
    // End of variables declaration//GEN-END:variables

}
